#!/usr/bin/env node

/**
 * arena-3d Interactive Setup
 *
 * Guides users through configuration and initial data fetch.
 */

import { createInterface } from 'readline';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');

function ask(rl, question, defaultVal = '') {
  const suffix = defaultVal ? ` [${defaultVal}]` : '';
  return new Promise(resolve => {
    rl.question(`  ${question}${suffix}: `, answer => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function main() {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log('');
  console.log('  ╔══════════════════════════════╗');
  console.log('  ║       arena-3d setup          ║');
  console.log('  ╚══════════════════════════════╝');
  console.log('');

  // Username or channels
  const username = await ask(rl, 'Are.na username (or Enter to use channel URLs)');

  let channels = [];
  if (!username) {
    const channelInput = await ask(rl, 'Channel URLs or slugs (comma-separated)');
    if (channelInput) {
      channels = channelInput.split(',').map(s => {
        s = s.trim();
        const match = s.match(/are\.na\/[^/]+\/([^/?#]+)/);
        return match ? match[1] : s;
      });
    }
  }

  if (!username && !channels.length) {
    console.log('\n  Error: You need either a username or channel URLs.');
    rl.close();
    process.exit(1);
  }

  // Token (required)
  console.log('');
  console.log('  An API token is required to fetch your data.');
  console.log('  It\'s free — see docs/TOKEN-GUIDE.md for a quick walkthrough.');
  console.log('');
  const token = await ask(rl, 'Are.na API token');

  if (!token) {
    console.log('');
    console.log('  No token provided. You need one to continue.');
    console.log('');
    console.log('  How to get a token (takes 2 minutes):');
    console.log('    1. Go to https://dev.are.na/oauth/applications');
    console.log('    2. Log in with your Are.na account');
    console.log('    3. Click "New Application"');
    console.log('    4. Name it anything (e.g. "arena-3d"), submit');
    console.log('    5. Copy the "Personal Access Token" and run setup again');
    console.log('');
    console.log('  Full guide: docs/TOKEN-GUIDE.md');
    console.log('');
    rl.close();
    process.exit(1);
  }

  // Display settings
  const title = await ask(rl, 'Page title', 'arena-3d');
  const accent = await ask(rl, 'Accent color', '#ccff00');

  // Layout
  const layout = await ask(rl, 'Default layout (spiral/galaxy/sphere/head)', 'spiral');

  rl.close();

  // Generate config
  const channelsLine = channels.length
    ? `    channels: ${JSON.stringify(channels)},`
    : `    // channels: [],`;

  const config = `/**
 * arena-3d Configuration
 * Generated by setup wizard
 */
export default {
  arena: {
    username: '${username}',
${channelsLine}
    token: '${token}',
  },

  display: {
    title: '${title}',
    subtitle: '/graph',
    accentColor: '${accent}',
  },

  graph: {
    defaultLayout: '${layout}',
  },
};
`;

  const configPath = join(ROOT, 'config', 'arena-3d.config.js');
  mkdirSync(join(ROOT, 'config'), { recursive: true });
  writeFileSync(configPath, config);
  console.log(`\n  [OK] Config written to config/arena-3d.config.js`);

  // Offer to fetch data
  console.log('\n  Fetching data from Are.na API...\n');

  try {
    execSync('node scripts/fetch.js', {
      cwd: ROOT,
      stdio: 'inherit',
      env: {
        ...process.env,
        ...(token ? { ARENA_ACCESS_TOKEN: token } : {}),
      },
    });
  } catch (e) {
    console.error('\n  Data fetch failed. You can retry with: npm run fetch');
    process.exit(1);
  }

  console.log('');
  console.log('  ╔══════════════════════════════╗');
  console.log('  ║       Setup complete!         ║');
  console.log('  ╚══════════════════════════════╝');
  console.log('');
  console.log('  Run `npm run dev` to see your graph.');
  console.log('');
}

main();
